# 아이스크림 성분 타입, 아이스크림 성분 타입별 총 주문량(TOTAL_ORDER)
# 총 주문량 기준 오름차순

SELECT I.INGREDIENT_TYPE, SUM(H.TOTAL_ORDER) TOTAL_ORDER
FROM FIRST_HALF H
         JOIN ICECREAM_INFO I
              ON H.FLAVOR = I.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER