# 2022년 10월 16일 ? 대여중 : 대여가능 (AVAILABILITY)
# 반납 날짜가 2022년 10월 16일 경우에도 대여중 표시
# 자동차 아이디 기준 내림차순

SELECT CAR_ID, MAX(IF('2022-10-16' BETWEEN START_DATE AND END_DATE, '대여중', '대여 가능')) AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC