# 완료된 거래의 총금액이 70만 원 이상인 경우 조회
# 총금액 기준으로 오름차순

SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD B
         JOIN USED_GOODS_USER U
              ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES