# 들어올 당시 중성화X - 나갈 당시 중성화된 동물 조회
# 아이디 기준 오름차순

SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID IN (SELECT ANIMAL_ID
                    FROM ANIMAL_INS
                    WHERE SEX_UPON_INTAKE LIKE '%Intact%')
  AND SEX_UPON_OUTCOME NOT LIKE '%Intact%'
ORDER BY 1

#

SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
         JOIN ANIMAL_OUTS O
              ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE 1 = 1
  AND I.SEX_UPON_INTAKE LIKE '%Intact%'
  AND O.SEX_UPON_OUTCOME NOT LIKE '%Intact%'
ORDER BY 1