# 2021년 가입
# 상품을 구매한 회원수 / 전체 회원 수(회원의 비율) - 년, 월 별로 출력
# 회원의 비율 - 소수점 두번째자리에서 반올림
# 년을 기준으로 오름차순 / 월을 기준으로 오름차순

SELECT DATE_FORMAT(O.SALES_DATE, '%Y') AS YEAR,
       DATE_FORMAT(O.SALES_DATE, '%m') AS MONTH,
       COUNT(DISTINCT U.USER_ID) AS PUCHASED_USERS,
       ROUND(COUNT(DISTINCT U.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE joined LIKE '2021%'), 1) AS PUCHASED_RATIO
FROM USER_INFO U
         JOIN ONLINE_SALE O
              ON U.USER_ID = O.USER_ID
WHERE U.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH