# 입양(OUTS)을 못 간 가장 오래 보호소에 있었던 동물 3마리
# 보호 시작일 오름차순

SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I
         LEFT JOIN ANIMAL_OUTS O
                   ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME
LIMIT 3