# 보호 시작일(INS) 보다 입양일(OUTS)이 더 빠른 동물 조회
# 보호 시작일 기준 오름차순

SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
         JOIN ANIMAL_OUTS O
              ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE TIMEDIFF(O.DATETIME, I.DATETIME) + 1 < 1
ORDER BY I.DATETIME

#

SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
         INNER JOIN ANIMAL_OUTS O
                    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME